dist: bionic
language: java

script:
- cd src && python check_names.py && cd ..

cache:
  directories:
  - target/lib
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - cat target/pmd.xml
branches:
  only:
  - master

matrix:
  include:
    - name : mysql
      jdk : oraclejdk11

      script:
        - sudo apt-get update && sudo apt-get install libssl-dev libmecab2 libjson-perl mecab-ipadic-utf8
        - sudo apt-get remove mysql-* && wget https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-server_8.0.20-1ubuntu18.04_amd64.deb-bundle.tar && tar -xvf mysql-server_8.0.20-1ubuntu18.04_amd64.deb-bundle.tar && yes | sudo dpkg -i *.deb
        - sudo mysql -e "CREATE USER 'sqlancer'@'localhost' IDENTIFIED BY 'sqlancer'; GRANT ALL PRIVILEGES ON * . * TO 'sqlancer'@'localhost';"
        - MYSQL_AVAILABLE=true mvn -Dtest=TestMySQL test
    - name: cockroachdb
      jdk : oraclejdk11
      before_install:
      - wget -qO- https://binaries.cockroachdb.com/cockroach-v20.1.2.linux-amd64.tgz | tar  xvz
      - cd cockroach-v20.1.2.linux-amd64/ && ./cockroach start-single-node --insecure &
      - cd cockroach-v20.1.2.linux-amd64/ && ./cockroach sql --insecure -e "CREATE USER sqlancer; GRANT admin to sqlancer"
      script:
      - COCKROACHDB_AVAILABLE=true mvn -Dtest=TestCockroachDB test
    - name: tidb
      jdk : oraclejdk11
      services:
      - docker
      before_install:
      - docker pull pingcap/tidb:latest
      - docker run --name tidb-server -d -p 4000:4000 pingcap/tidb:latest
      - sleep 15
      - sudo mysql -h 127.0.0.1 -P 4000 -u root -D test -e "CREATE USER 'sqlancer'@'%' IDENTIFIED WITH mysql_native_password BY 'sqlancer'; GRANT ALL PRIVILEGES ON *.* TO 'sqlancer'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"
      script:
        - TIDB_AVAILABLE=true mvn -Dtest=TestTiDB test
    - name: sqlite
      jdk : oraclejdk11
      script:
        - mvn -Dtest=TestSQLite3 test
    - name: duckdb
      jdk : oraclejdk11
      script: 
        - mvn -Dtest=TestDuckDB test
    - name: duckdb (java 8)
      jdk : openjdk8
      script:
        - mvn -Dtest=TestDuckDB test
    - name: misc
      jdk : oraclejdk11
      script:
        - mvn '-Dtest=!sqlancer.dbms.**' test
    - name: postgres
      before_install:
      - sudo apt-get update
      - sudo apt-get --yes remove postgresql\*
      - sudo apt-get install -y postgresql-12 postgresql-client-12
      - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
      - sudo cp /etc/postgresql/{10,12}/main/pg_hba.conf
      - sudo service postgresql restart 12  
      addons:
        postgresql: "12.3"
      env:
        global:
          - PGPORT=5432
      services:
        - postgresql
      before_script:
        - sudo apt-get install locales
        - psql -c "CREATE ROLE sqlancer SUPERUSER LOGIN CREATEDB PASSWORD 'sqlancer';" -U postgres
        - createdb test -U postgres
      script:
        - POSTGRES_AVAILABLE=true mvn -Dtest=TestPostgres test
